version: 2
sphinx:
  # Path to your Sphinx configuration file.
  configuration: conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
  - requirements: requirements.txt

# Build PDF & HTML
formats:
    - pdf
    - htmlzip
python:
  version: 3.7
  install:
    - requirements: requirements.txt
